<?xml version="1.0" encoding="UTF-8"?>
<testrun name="recfun" project="recfun" tests="11" started="11" failures="0" errors="6" ignored="0">
  <testsuite name="recfun.BalanceSuite" time="0.114">
    <testcase name="'" classname="if (zero? x" time="0.016"/>
    <testcase name="'I told him ...' is balanced." classname="recfun.BalanceSuite" time="0.0"/>
    <testcase name="':-)' is unbalanced." classname="recfun.BalanceSuite" time="0.096">
      <error>org.scalatest.exceptions.TestFailedException
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:316)
	at recfun.BalanceSuite.newAssertionFailedException(BalanceSuite.scala:9)
	at org.scalatest.Assertions$class.assert(Assertions.scala:311)
	at recfun.BalanceSuite.assert(BalanceSuite.scala:9)
	at recfun.BalanceSuite$$anonfun$3.apply$mcV$sp(BalanceSuite.scala:21)
	at recfun.BalanceSuite$$anonfun$3.apply(BalanceSuite.scala:21)
	at recfun.BalanceSuite$$anonfun$3.apply(BalanceSuite.scala:21)
	at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1265)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1974)
	at recfun.BalanceSuite.withFixture(BalanceSuite.scala:9)
	at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1262)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:198)
	at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1271)
	at recfun.BalanceSuite.runTest(BalanceSuite.scala:9)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:260)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:249)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:76)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:249)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:326)
	at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1304)
	at recfun.BalanceSuite.runTests(BalanceSuite.scala:9)
	at org.scalatest.Suite$class.run(Suite.scala:2303)
	at recfun.BalanceSuite.org$scalatest$FunSuite$$super$run(BalanceSuite.scala:9)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:362)
	at org.scalatest.FunSuite$class.run(FunSuite.scala:1310)
	at recfun.BalanceSuite.run(BalanceSuite.scala:9)
	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:94)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</error>
    </testcase>
    <testcase name="Counting is not enough." classname="recfun.BalanceSuite" time="0.002">
      <error>org.scalatest.exceptions.TestFailedException
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:316)
	at recfun.BalanceSuite.newAssertionFailedException(BalanceSuite.scala:9)
	at org.scalatest.Assertions$class.assert(Assertions.scala:311)
	at recfun.BalanceSuite.assert(BalanceSuite.scala:9)
	at recfun.BalanceSuite$$anonfun$4.apply$mcV$sp(BalanceSuite.scala:25)
	at recfun.BalanceSuite$$anonfun$4.apply(BalanceSuite.scala:25)
	at recfun.BalanceSuite$$anonfun$4.apply(BalanceSuite.scala:25)
	at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1265)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1974)
	at recfun.BalanceSuite.withFixture(BalanceSuite.scala:9)
	at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1262)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:198)
	at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1271)
	at recfun.BalanceSuite.runTest(BalanceSuite.scala:9)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:260)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:249)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:76)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:249)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:326)
	at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1304)
	at recfun.BalanceSuite.runTests(BalanceSuite.scala:9)
	at org.scalatest.Suite$class.run(Suite.scala:2303)
	at recfun.BalanceSuite.org$scalatest$FunSuite$$super$run(BalanceSuite.scala:9)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:362)
	at org.scalatest.FunSuite$class.run(FunSuite.scala:1310)
	at recfun.BalanceSuite.run(BalanceSuite.scala:9)
	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:94)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</error>
    </testcase>
  </testsuite>
  <testsuite name="recfun.PascalSuite" time="0.0">
    <testcase name="col=0,row=2" classname="recfun.PascalSuite" time="0.0"/>
    <testcase name="col=1,row=2" classname="recfun.PascalSuite" time="0.0"/>
    <testcase name="col=1,row=3" classname="recfun.PascalSuite" time="0.0"/>
  </testsuite>
  <testsuite name="recfun.CountChangeSuite" time="0.024">
    <testcase name="manual" classname="recfun.CountChangeSuite" time="0.018">
      <error>org.scalatest.exceptions.TestFailedException: 1 did not equal 3
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:318)
	at recfun.CountChangeSuite.newAssertionFailedException(CountChangeSuite.scala:9)
	at org.scalatest.Assertions$class.assert(Assertions.scala:401)
	at recfun.CountChangeSuite.assert(CountChangeSuite.scala:9)
	at recfun.CountChangeSuite$$anonfun$1.apply$mcV$sp(CountChangeSuite.scala:12)
	at recfun.CountChangeSuite$$anonfun$1.apply(CountChangeSuite.scala:12)
	at recfun.CountChangeSuite$$anonfun$1.apply(CountChangeSuite.scala:12)
	at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1265)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1974)
	at recfun.CountChangeSuite.withFixture(CountChangeSuite.scala:9)
	at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1262)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:198)
	at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1271)
	at recfun.CountChangeSuite.runTest(CountChangeSuite.scala:9)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:260)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:249)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:76)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:249)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:326)
	at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1304)
	at recfun.CountChangeSuite.runTests(CountChangeSuite.scala:9)
	at org.scalatest.Suite$class.run(Suite.scala:2303)
	at recfun.CountChangeSuite.org$scalatest$FunSuite$$super$run(CountChangeSuite.scala:9)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:362)
	at org.scalatest.FunSuite$class.run(FunSuite.scala:1310)
	at recfun.CountChangeSuite.run(CountChangeSuite.scala:9)
	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:94)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</error>
    </testcase>
    <testcase name="sorted CHF" classname="recfun.CountChangeSuite" time="0.002">
      <error>org.scalatest.exceptions.TestFailedException: 1 did not equal 1022
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:318)
	at recfun.CountChangeSuite.newAssertionFailedException(CountChangeSuite.scala:9)
	at org.scalatest.Assertions$class.assert(Assertions.scala:401)
	at recfun.CountChangeSuite.assert(CountChangeSuite.scala:9)
	at recfun.CountChangeSuite$$anonfun$2.apply$mcV$sp(CountChangeSuite.scala:16)
	at recfun.CountChangeSuite$$anonfun$2.apply(CountChangeSuite.scala:16)
	at recfun.CountChangeSuite$$anonfun$2.apply(CountChangeSuite.scala:16)
	at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1265)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1974)
	at recfun.CountChangeSuite.withFixture(CountChangeSuite.scala:9)
	at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1262)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:198)
	at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1271)
	at recfun.CountChangeSuite.runTest(CountChangeSuite.scala:9)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:260)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:249)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:76)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:249)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:326)
	at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1304)
	at recfun.CountChangeSuite.runTests(CountChangeSuite.scala:9)
	at org.scalatest.Suite$class.run(Suite.scala:2303)
	at recfun.CountChangeSuite.org$scalatest$FunSuite$$super$run(CountChangeSuite.scala:9)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:362)
	at org.scalatest.FunSuite$class.run(FunSuite.scala:1310)
	at recfun.CountChangeSuite.run(CountChangeSuite.scala:9)
	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:94)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</error>
    </testcase>
    <testcase name="no pennies" classname="recfun.CountChangeSuite" time="0.002">
      <error>org.scalatest.exceptions.TestFailedException: 1 did not equal 0
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:318)
	at recfun.CountChangeSuite.newAssertionFailedException(CountChangeSuite.scala:9)
	at org.scalatest.Assertions$class.assert(Assertions.scala:401)
	at recfun.CountChangeSuite.assert(CountChangeSuite.scala:9)
	at recfun.CountChangeSuite$$anonfun$3.apply$mcV$sp(CountChangeSuite.scala:20)
	at recfun.CountChangeSuite$$anonfun$3.apply(CountChangeSuite.scala:20)
	at recfun.CountChangeSuite$$anonfun$3.apply(CountChangeSuite.scala:20)
	at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1265)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1974)
	at recfun.CountChangeSuite.withFixture(CountChangeSuite.scala:9)
	at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1262)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:198)
	at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1271)
	at recfun.CountChangeSuite.runTest(CountChangeSuite.scala:9)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:260)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:249)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:76)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:249)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:326)
	at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1304)
	at recfun.CountChangeSuite.runTests(CountChangeSuite.scala:9)
	at org.scalatest.Suite$class.run(Suite.scala:2303)
	at recfun.CountChangeSuite.org$scalatest$FunSuite$$super$run(CountChangeSuite.scala:9)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:362)
	at org.scalatest.FunSuite$class.run(FunSuite.scala:1310)
	at recfun.CountChangeSuite.run(CountChangeSuite.scala:9)
	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:94)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</error>
    </testcase>
    <testcase name="unsorted CHF" classname="recfun.CountChangeSuite" time="0.001">
      <error>org.scalatest.exceptions.TestFailedException: 1 did not equal 1022
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:318)
	at recfun.CountChangeSuite.newAssertionFailedException(CountChangeSuite.scala:9)
	at org.scalatest.Assertions$class.assert(Assertions.scala:401)
	at recfun.CountChangeSuite.assert(CountChangeSuite.scala:9)
	at recfun.CountChangeSuite$$anonfun$4.apply$mcV$sp(CountChangeSuite.scala:24)
	at recfun.CountChangeSuite$$anonfun$4.apply(CountChangeSuite.scala:24)
	at recfun.CountChangeSuite$$anonfun$4.apply(CountChangeSuite.scala:24)
	at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1265)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1974)
	at recfun.CountChangeSuite.withFixture(CountChangeSuite.scala:9)
	at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1262)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:198)
	at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1271)
	at recfun.CountChangeSuite.runTest(CountChangeSuite.scala:9)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:260)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:249)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
	at scala.collection.immutable.List.foreach(List.scala:76)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:249)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:326)
	at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1304)
	at recfun.CountChangeSuite.runTests(CountChangeSuite.scala:9)
	at org.scalatest.Suite$class.run(Suite.scala:2303)
	at recfun.CountChangeSuite.org$scalatest$FunSuite$$super$run(CountChangeSuite.scala:9)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:362)
	at org.scalatest.FunSuite$class.run(FunSuite.scala:1310)
	at recfun.CountChangeSuite.run(CountChangeSuite.scala:9)
	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:94)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</error>
    </testcase>
  </testsuite>
</testrun>
